usuarios/applications/home/urls.py
from django.contrib import admin
from django.urls import path

from .views import *


app_name= 'home_app'
urlpatterns = [
    path('home/', Homepage.as_view(), name='home'),
]

usuarios/applications/users/urls.py
from django.contrib import admin
from django.core.exceptions import AppRegistryNotReady
from django.urls import path

from .views import *

app_name='users_app'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='registro'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('update-password/', UpdatePassword.as_view(), name='update-password'),
    path('user-verification/<pk>', CodeVerificationView.as_view(), name='user-verification'),
    
]

usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
]

usuarios/applications/home/models.py
from django.db import models

# Create your models here.

usuarios/applications/home/views.py
from django.shortcuts import render
from django.urls.base import reverse_lazy

from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.




class Homepage(LoginRequiredMixin,TemplateView):
    template_name = "home/index.html"
    login_url = reverse_lazy('users_app:login')

usuarios/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Panel de Usuario</h1>
    <h3>Bienvenido: {{user}}</h3>

    <ul>
        <li><a href="{% url 'users_app:logout' %}">Cerrar sesión</a></li>
        <li><a href="{% url 'users_app:update-password' %}">Actualizar datos</a></li>
    </ul>
</body>
</html>